### ISSUE TITLE
Flagg med direkte styling av P elementer

### ISSUE THREAD

**Issue by felixlhh** [felixlhh/GROUP-11-GRP-REPOSITORY#14]

**Comment by Shekina22** [comment]
jeg begynte med å lage et "html" file. hvor jeg deretter fylte inn "Doctype", "<head></head> og <body></body>. i dette fylte jeg inn Css filer slik at Arman kunne designe flaggene etter jeg fikk push det opp til min branch.

**Comment by arman7203** [comment]
Jeg styla p elementet og la til farger på hver av dem. Tokk backround-color til fargene som flagget trengte og color farge for at skrifta skulle forsvinne. Brukte margin auto for at de skulle fjerne avstanden på p elementet og plassere seg i midten. Brukte box-shadow for at flagget skal se bedre ut.
