### ISSUE TITLE
Deloppgave 1 - Flagg ved å style <p> elementer direkte. 

### ISSUE THREAD

**Issue by felixlhh** [felixlhh/GROUP-11-GRP-REPOSITORY#4]
Oppgaven består av å lage det tyske flagget. Shekina lager oppsettet i HTML filen, og Arman styler det derretter i CSS.

**Comment by Shekina22** [comment]
For denne oppgaven har jeg laget klar html, slik at det skal være lett å designe med bruk av Css. 
Etter oppsette, fikk jeg "push" kodingen til min egen "branch", slik at Arman kunne "pull" hente og designe.

**Comment by arman7203** [comment]
Jeg pulla html filen og styla det med <style> element. Altså desginet den med farger osv. Etterpå pusha jeg det til min branch og merga vi det til main
