### ISSUE TITLE
Deloppgave 2 - Lage et flagg med <p> elementet og style ved bruk av "id" og "class".

### ISSUE THREAD

**Issue by felixlhh** [felixlhh/GROUP-11-GRP-REPOSITORY#5]
Deloppgaven består av å lage et HTML dokument, og deretter bruke "id" og "class" for å style <P> elementer.

**Comment by Hanegalen** [comment]
Lastet opp HTML-kode for deloppgave 2. Filnavn "cssflagg.html".

**Comment by felixlhh** [comment]
Stylet ""<p>"" elementene til et italiensk flagg.

**Comment by felixlhh** [comment]
Noterer også at det ikke er mulig å skrive P-element slik man gjør det i HTML. Virker som at Github oppfatter dette som html kode.
