### ISSUE TITLE
Deloppgave 3 - Lage et flagg ved bruk av CANVAS API

### ISSUE THREAD

**Issue by felixlhh** [felixlhh/GROUP-11-GRP-REPOSITORY#6]
Denne oppgaven befaller Steven!

**Comment by StevenMTN** [comment]
Fil: "CANVAS.html" har flagget til Romania, kodet via CANVAS API HTML5. 
Pull request hadde ingen konflikt med main branch.

**Comment by StevenMTN** [comment]
Prosessen:
1. Lagde en vanlig layout til en HTML fil. 
2. Lage en Canvas på <body>. Størrelsen/ratio til Canvasen var basert på Romania sin flagg proporsjoner (3/2).
3. Skrive ut funksjon for å få fargen på Canvas. 
4. Redigere "width" og "height" på fargene. 
5. Siste "Sugar"-edit med posisjonering av flagget og hyperlink til Romania.
